==== 6.6.2.3  Capability metadata

The <Capability> element of the service metadata names the actual operations that are supported by the server, the output formats offered for those operations, and the URL prefix for each operation. The XML schema includes placeholders for Distributed Computing Platforms other than HTTP, but currently only the HTTP platform is defined.  

* *Layers and styles*: Each available map is advertised by a <Layer> element in the service metadata. A server shall include at least one <Layer> element for each map layer offered.
* *Layer properties:* The <Layer> element can enclose child elements providing metadata about the Layer. The values of some of these elements can be inherited by subsidiary layers. The following metadata elements are available:
** *Title:* A <Title> is mandatory for all layers; it is a human-readable string for presentation in a menu. The Title is not inherited by child Layers.
** *Name*: If, and only if, a layer has a <Name>, then it is a map layer that can be requested by using that Name in the LAYERS parameter of a GetMap request. If the layer has a Title but no Name, then that layer is only a category title for all the layers nested within. A containing category itself may include a Name by which a map portraying all of the nested layers can be requested at once. For example, a parent layer "Roads" may have children “Interstates” and “State Highways” and allow the user to request either child individually or both together.
** The elements <**Abstract**> and <**KeywordList**> are optional in the base standard. Abstract is a narrative description of the map layer. KeywordList contains zero or more <Keyword> elements to aid in catalogue searches.  +

--
::
*_Requirement 11: A DGIWG WMS server shall include the following information in the abstract element of the service metadata: "This service implements the DGIWG WMS 1.3 profile version 1.0."_*  +

::
*_Requirement 12: A DGIWG WMS server shall provide a minimum keyword list based on the DFDD groups:_*
*** Aeronautical  
*** Biota  
*** Characteristics  
*** Demarcation  
*** Hydrography and Oceanography  
*** Industries and Services  
*** Metadata and References  
*** Military  
*** Names and Designations  
*** Physiography  
*** Socio-economic Geography  
*** Transportation  
*** Weather and Climate  
--

[Note]
NOTE:  Additional keywords may be added to the list as appropriate to support data discovery.
--

::
**** Zero or more Styles may be advertised for a Layer or collection of layers using <Style> elements, each of which shall have <Name> and <Title> elements.
***** The style's *Name* is used in the Map request STYLES parameter.
***** The *Title* is a human-readable string. If only a single style is available, that style is known as the “default” style and need not be advertised by the server.

::
*_Requirement 13: A DGIWG WMS server shall provide information on the supported styles._*
::
*_Requirement 14: A DGIWG WMS server shall always provide at least one style element and that style shall be advertised even if it's only the default style._*

::
*_Requirement 15: The MaxWidth and MaxHeight shall be greater or equal to 800 pixels._*

::
***** <LegendURL> contains the location of an image of a map legend appropriate to the enclosing style.

::
*_Requirement 16: Each vector data layer's style shall have an associated legend, available as an image in one of the following formats: PNG, GIF or JPEG._*

*Recommendation 2: It is recommended to also provide legends for raster layers representing numeric data like for instance elevation or temperature data.*

::
*_Requirement 17: This legend shall be accessible online at the URL specified by LegendURL._*

***** *Scale denominators*: The <MinScaleDenominator> and <MaxScaleDenominator> elements define the range of scales for which it is appropriate to generate a map of a Layer.

::
*_Requirement 18: A DGIWG WMS server shall provide scale denominators for all layers it provides._*

::
*_Requirement 19: The <MinScaleDenominator> value shall always be less than or equal to the <MaxScaleDenominator> value._*

*Recommendation 4: A DGIWG WMS service should be configured to serve requests that range from at least 4x to at least 0.25x the native scale(s) or resolution(s) of the underlying datasets".*

NOTE: Users should be aware that changing the resolution at a range of 4 times to 0.25 times effects the accuracy of the displayed data significantly and will influence the usability of the data for certain use cases (e.g. measurements in the map).

::
***** *Sample dimensions:* Some geographic information may be available at other dimensions (for example, satellite images in different wavelength bands). The dimensions other than the four space-time dimensions are referred to as “sample dimensions. A DGIWG WMS server may allow for requesting a particular layer along one or more dimensional axes other than time or elevation.

***** *MetadataURL:* A server should use one or more <MetadataURL> elements to offer detailed, standardized metadata about the data corresponding to a particular layer. The “type” attribute indicates the standard to which the metadata complies**.** Two “type” attribute values are defined in ISO 19128:2005, "ISO 19115:2003" and “FGDC:1998”. The enclosed <Format> element indicates the file format MIME type of the metadata record.

*Recommendation 5: In an SDI like architecture, a DGIWG WMS server should provide a link to the metadata resource via a resolvable URL for example to a CSW server.*

::
*** FeatureListURL: A server may use a <FeatureListURL> element to point to a list of the features represented in a Layer. The enclosed Format element indicates the file format MIME type of the feature list.  
  
-- 
::
*_Requirement 20: If the GetCapabilities document identifies support for FeatureListURL then the list of features that are in the particular layer shall be resolvable through the provided URL._*

*** DataURL: A server may use DataURL to offer a link to the underlying data represented by a particular layer. The enclosed Format element indicates the file format MIME type of the data file.  
  
--  
::
*_Requirement 21: If the GetCapabilities document identifies support for DataURL then the underlying data of the particular layer shall be resolvable through the provided URL._*

*** *Layer attributes:* A <Layer> may have zero or more of the following XML attributes: queryable, cascaded, opaque, noSubsets, fixedWidth, and fixedHeight. All of these attributes are optional and default to 0. The meaning of each attribute is summarized in Table 4

[cols=",,,",options="header",]
|========================================================================================
|*Attribute* 

a| *OGC* *allowed values*

|*DGIWG* *allowed values* 

|*Meaning (0 is default value)*
|*queryable* 

a|0, false,

1, true a
|0, false,1, 

true a| 0, false: layer is not queryable. 

1, true: layer is queryable.

|*cascaded* |0, 

positive integer a|
0,

positive integer

 a|
0: layer has not been retransmitted by a Cascading Map Server.

n: layer has been retransmitted _n_ times.

|*Opaque* a|
0, false,

1, true

 a|
0, false,

1, true

 a|
0, false: map data represents vector features that probably do not completely fill space.

1, true: map data are mostly or completely opaque.

|*noSubsets* a|
0, false,

1, true

 |0, false, a|
0, false: WMS can map a subset of the full bounding box.

1, true: WMS can only map the entire bounding box.

|*fixedWidth* a|
0,

positive integer

 |0, a|
0: WMS can produce map of arbitrary width.

nonzero: value is fixed map width that cannot be changed by the WMS.

|*fixedHeight* a|
0,

positive integer

 |0, a|
0: WMS can produce map of arbitrary height.

nonzero: value is fixed map height that cannot be changed by the WMS.

|========================================================================================

*_Table 4: Layer attributes_*

::
*_Requirement 22: A DGIWG WMS server shall provide the Layer Attributes according to Table 4.__*

*Recommendation 6: _A DGIWG WMS server offering vector layers should be queryable_*

The Layer metadata may also include three optional attributes that indicate a map server that is less functional than a normal WMS, because it is not able to extract a subset of a larger dataset or because it only serves maps of a fixed size and cannot resize them.

When set to a true value, *noSubsets* indicates that the server is not able to make a map of a geographic area other than the layer's bounding box.

When present and nonzero, *fixedWidth* and *fixedHeight* indicate that the server is not able to produce a map of the layer at a width and height different from the fixed sizes indicated.

According to Table 4 a DGIWG WMS server provides only subsettable (nosubsets=0) and resizable (fixedWidth=0 and fixedHeight=0) layers. As the 0 values are the default values, they do not have to be included explicitly for all layers.
