= Table of Contents

|================================================
a|== 1.  Introduction |1  +
a|== 2.  Scope |2  
a|== 3.  Conformance |2  
a|== 4.  Normative and informative References |2  
a|=== 4.1. Normative references |2  
a|=== 4.2. Informative References |3  
a|== 5. Terms, definitions, and abbreviations |3  
a|=== 5.1. Definitions |3  
a|=== 5.2. Abbreviations |3  
a|== 6. DGIWG WMS Profile (normative) |6  
a|=== 6.1. Introduction |6  
a|=== 6.2. Normative Requirements |6  
a|=== 6.3. Non-Normative Recommendations for Implementation |8  
a|=== 6.4. Service Type |9  
a|=== 6.5. Basic service elements |9  
a|==== 6.5.1.  Version number |9  
a|==== 6.5.2.  Binding |9  
a|==== 6.5.3.  Output Formats |9  
a|==== 6.5.4.  Coordinate Systems |10  
a|==== 6.5.5.  Request Parameter Rules |11  
a|=== 6.6. Operations |12  
a|==== 6.6.1. GetCapabilities Operation Request |12    
a|==== 6.6.2. GetCapabilities Operation Response |12    
a|==== 6.6.3. GetMap Operation Request |17    
a|==== 6.6.4. GetMap Response |19    
a|==== 6.6.5. GetFeatureInfo Operation Request |19    
a|==== 6.6.6. GetFeatureInfo response |21    
a|== 7. Quality of Service |22  
a|=== 7.1. Performance |22  
a|=== 7.2. Capacity |22  
a|=== 7.3. Availability |22  

a|== Annex A – Abstract Test Suite |23
a|=== A.1 DGIWG Service Type |23
a|==== A.1.1 DGIWG Service Type |23  
a|==== A.1.2 DGIWG WMS Binding |23
a|==== A.1.3 DGIWG WMS Output format |23  
a|==== A.1.4 DGIWG WMS CRS |24  
a|==== A.1.5 DGIWG WMS Request Parameters - Exceptions |24  
a|=== A.2 DGIWG WMS Operations |24  
a|==== A.2.1 DGIWG WMS GetCapabilities request |24  
a|==== A.2.2 DGIWG WMS GetCapabilites Response |24  
a|==== A.2.3 DGIWG WMS GetMap Request |25  
a|==== A.2.4 DGIWG GetFeatureInfo Operation Request - FEATURE_COUNT |26  
a|==== A.2.5 DGIWG GetFeatureInfo Operation Request - EXCEPTIONS |26  
a|==== A.2.6 DGIWG WMS GetFeatureInfo Response |26  

a|== Annex B – Use cases |27  
a|== Annex C – Examples |29  
a|== Annex D – Client Requirements and Recommendations |35  
a|== Annex E – UTM Grid and MGRS Grid System Handling in WMS Clients and Portals |37  

a|==  List of Tables |
a|=== Table 1: DGIWG WMS Profile Normative Server Requirements |8  
a|=== Table 2: DGIWG WMS Profile Non-normative Recommendations for Server Implementation |9  
a|=== Table 3: The parameters of a GetCapabilities request URL as per Normative Reference [1] |12  
a|=== Table 4: Layer attributes |16  
a|=== Table 5: GetMap request parameters |17  
a|=== Table 6: GetFeatureInfo Request parameters |20  
a|=== Table 7: Normative client requirements |36 
a|=== Table 8: DGIWG WMS Profile Non-normative Recommendations for Client Implementation |36
|================================================
